version: '3.8'

services:
  relay-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MAX_RECONNECT_ATTEMPTS=5
      - RECONNECT_INTERVAL=2
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 